version: "3"
services:
  trellis:
    image: trellisldp/trellis-ext-db:latest
    ports:
      - 8080:8080
    links:
      - postgres
    depends_on:
      - postgres
      - migration
    volumes:
      - ./trellis/etc:/opt/trellis/etc
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: sinopia
      POSTGRES_DB: sinopia
      POSTGRES_PASSWORD: S1n0p1a
      PGDATA: /var/lib/postgresql/data/pgdata/mydata
    ports:
      - 5432:5432
  migration:
    image: trellisldp/trellis-ext-db:latest
    command: ["/opt/trellis/bin/trellis-db", "db", "migrate", "/opt/trellis/etc/config.yml"]
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./trellis/etc:/opt/trellis/etc
