FROM trellisldp/trellis-ext-db:0.2.2

# Our configured repackaging of the upstream container
LABEL maintainer="SUL Infrastructure Team <dlss-infrastructure-team@lists.stanford.edu>"

COPY trellis/etc/ /opt/trellis/etc/

RUN ls -lha /opt/trellis/etc/
