version: "3"
services:
  trellis:
    container_name: trellis_server
    build:
      context: .
      dockerfile: Dockerfile.trellis-ext-db
    ports:
      - 8080:8080
      - 8081:8081
    links:
      - postgres
    depends_on:
      - postgres
      - migration
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:8081/healthcheck"]
      retries: 5
  postgres:
    container_name: postgres_server
    image: postgres:latest
    environment:
      POSTGRES_USER: sinopia
      POSTGRES_DB: sinopia
      POSTGRES_PASSWORD: S1n0p1a
      PGDATA: /var/lib/postgresql/data/pgdata/mydata
    ports:
      - 5432:5432
  migration:
    container_name: trellis_migration
    build:
      context: .
      dockerfile: Dockerfile.trellis-ext-db
    command: ["/opt/trellis/bin/trellis-db", "db", "migrate", "/opt/trellis/etc/config.yml"]
    links:
      - postgres
    depends_on:
      - postgres
