version: "3"
services:
  broker:
    image: rmohr/activemq
    ports:
      - 61616:61616
      - 61613:61613
      - 8161:8161
  platformdata:
    image: ld4p/sinopia_acl:0.2
    environment:
      INSIDE_CONTAINER: 'true'
      TRELLIS_BASE_URL: http://platform:8080
      COGNITO_ADMIN_PASSWORD: "${COGNITO_ADMIN_PASSWORD}" # add to .env file (DO NOT CHECK IN)
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}" # add to .env file (DO NOT CHECK IN)
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}" # add to .env file (DO NOT CHECK IN)
    command: dockerize -wait tcp://platform:8080 -timeout 3m bin/migrate
    depends_on:
      - platform
  platform:
    build:
      context: .
      dockerfile: Dockerfile.trellis-ext-db
    environment:
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID:-us-west-2_CGd9Wq136}
      AWS_REGION: ${AWS_COGNITO_REGION:-us-west-2}
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - database
      - broker
      - migration
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: sinopia
      POSTGRES_DB: sinopia
      POSTGRES_PASSWORD: S1n0p1a
      PGDATA: /var/lib/postgresql/data/pgdata/mydata
    ports:
      - 5432:5432
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - 9200:9200
      - 9300:9300
  migration:
    build:
      context: .
      dockerfile: Dockerfile.trellis-ext-db
    command: ["/opt/trellis/bin/trellis-db", "db", "migrate", "/opt/trellis/etc/config.yml"]
    depends_on:
      - database
