swagger: '2.0'
consumes:
  - "application/json+ld"
produces:
  - "application/json+ld"
basePath: /
info:
  description: Sinopia Server. Supports CRUD, following loosely LDP, on Sinopia resources. Top level requires special authorization for creating a group's graph (i.e. PCC, Stanford, etc.).
  version: 1.0.0
  title: Sinopia Server
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
securityDefinitions:
  RemoteUser:
    type: apiKey
    in: header
    name: On-Behalf-Of
paths:
  '/repository':
    get:
      summary: Get metadata for the base container.
      description: Get the RDF metadata (default serialization is JSON-LD) for the base container.
      operationId: getBase
      tags:
        - LDP
      security:
        - RemoteUser: []
      responses:
        '200':
          description: Successful base container response.
          headers:
            type:
              description: Target URI matching type of container (basic).
              type: string
              format: URI
            Content-Type:
              description: Content-Type for resource
              type: string
              format: URI
          schema:
            $ref: '#/definitions/LDPContainer'
        '404':
          description: Unable to find the base container.
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: Unsuccessful response
    post:
      summary: Create new Group within the base container.
      description: Create a new Group (defined via JSON-LD in payload) within the base container.
      tags:
        - LDP
      parameters:
        - name: Slug
          description: The group (ldp:Container) who is defining it's own entities or graph within Sinopia.
          in: header
          required: false
          type: string
        - name: groupMD
          in: body
          description: Group metadata to insert into base container and describe the group.
          required: true
          schema:
            $ref: '#/definitions/Resource'
        - name: Content-Type
          in: header
          description: Content-Type of resource, with preference for JSON-LD.
          required: false
          type: string
      responses:
        "201":
          description: Successful Group resource creation.
          headers:
            Location:
              description: URI of the newly created resource
              type: string
              format: uri
        "401":
          description: Unsuccessful authentication.
        "403":
          description: You are not allow to perform this action.
        "404":
          description: Unable to find base container.
        "405":
          description: Method not allowed.
          headers:
            Allow:
              description: HTTP methods allowed
              type: array
              items:
                type: string
        "409":
          description: Group (based on URI and identifier) already exists.
        default:
          description: Unsuccessful response
    put:
      summary: Update metadata on base container.
      description: Update metadata of base container with new metadata defined via JSON-LD in payload. Performs overwrite, not partial update.
      tags:
        - LDP
      parameters:
        - name: Metadata
          in: body
          description: New base container metadata to assert on the container.
          required: true
          schema:
            $ref: '#/definitions/Resource'
        - name: Content-Type
          in: header
          description: Content-Type of resource
          required: false
          type: string
      responses:
        "200":
          description: Successful response
        "201":
          description: Successful creation
          headers:
            Location:
              description: URI to created resource
              type: string
        "404":
          description: Unable to find container
        "405":
          description: Method not allowed
          headers:
            Allow:
              description: HTTP methods allowed
              type: array
              items:
                type: string
        "409":
          description: URI Already Exists
        default:
          description: Unsuccessful response
    options:
      tags:
        - LDP
      description: Gets options for HTTP methods to utilize for the base container.
      responses:
        "200":
          description: Successful response
          headers:
            Accept:
              type: array
              items:
                type: string
            Accept-Patch:
              type: array
              items:
                type: string
        "404":
          description: Unable to find base container
        default:
          description: Unsuccessful response
    head:
      tags:
        - LDP
      summary: Get headers only of base container request.
      description: Gets the header values that would normally be found in the header of GET on base container
      responses:
        "200":
          description: Successful response
          headers:
            Allow:
              type: array
              items:
                type: string
            Link:
              type: array
              items:
                type: string
                format: uri
        "404":
          description: Unable to find container
        default:
          description: Unsuccessful response
  '/repository/{groupID}':
    get:
      summary: Query for RDF about a Group.
      description: Get the RDF (default, JSON-LD) for a Group.
      operationId: getGroup
      security:
        - RemoteUser: []
      parameters:
        - name: groupID
          description: The group who is defining it's own resources or graph within Sinopia. LDP Container to get.
          in: path
          required: true
          type: string
          format: UUID
      responses:
        '200':
          description: Successful response.
          headers:
            type:
              description: Target URI matching type of container
              type: string
            Content-Type:
              description: Content-Type for resource
              type: string
          schema:
            $ref: '#/definitions/LDPContainer'
        '404':
          description: Unable to find the specified Group.
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: Unsuccessful response
    post:
      summary: Create new Group.
      description: Create a resource (defined via JSON-LD in payload) within a Group.
      tags:
        - LDP
      parameters:
        - name: groupID
          description: The group (ldp:Container) who is defining it's own resources or graph within Sinopia.
          in: path
          required: true
          type: string
          format: UUID
        - name: resource
          in: body
          description: Resource to insert into container
          required: true
          schema:
            $ref: '#/definitions/Resource'
        - name: Slug
          in: header
          description: Suggested URI for resource
          required: false
          type: string
        - name: Content-Type
          in: header
          description: Content-Type of resource
          required: false
          type: string
      responses:
        "200":
          description: Successful response
        "201":
          description: Successful creation
          headers:
            Location:
              description: URI to created resource
              type: string
        "404":
          description: Unable to find container
        "405":
          description: Method not allowed
          headers:
            Allow:
              description: HTTP methods allowed
              type: array
              items:
                type: string
        "409":
          description: URI Already Exists

        default:
          description: Unsuccessful response
    put:
      tags:
        - LDP
      description: Updates the group description.
      parameters:
        - name: groupID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: UUID
        - name: resource
          in: body
          description: Resource to insert into container
          required: true
          schema:
            $ref: '#/definitions/Resource'
        - name: Slug
          in: header
          description: Suggested URI for resource
          required: false
          type: string
        - name: Content-Type
          in: header
          description: Content-Type of resource
          required: false
          type: string
      responses:
        "200":
          description: Successful response
        "404":
          description: Unable to find container
        "405":
          description: Method not allowed
          headers:
            Allow:
              description: HTTP methods allowed
              type: array
              items:
                type: string
        "409":
          description: URI Already Exists
        default:
          description: Unsuccessful response
    patch:
      tags:
        - LDP
      description: |
        Updates LDP container
      parameters:
        - name: groupID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: UUID
        - name: resource
          in: body
          description: Resource to insert into container
          required: true
          schema:
            $ref: '#/definitions/Resource'
      responses:
        "200":
          description: Successful response
        "404":
          description: Unable to find container
        "405":
          description: Method not allowed
          headers:
            Allow:
              description: HTTP methods allowed
              type: array
              items:
                type: string
        "406":
          description: Violates constraints on resource modification
          headers:
            Accept-Patch:
                type: array
                items:
                  type: string
        default:
          description: Unsuccessful response
    delete:
      tags:
        - LDP
      description: |
        Deletes LDP container
      parameters:
        - name: groupID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: UUID
      responses:
        "200":
          description: Successful response
        "404":
          description: Unable to find container
        "405":
          description: Method not allowed
          headers:
            Allow:
              description: HTTP methods allowed
              type: array
              items:
                type: string
        default:
          description: Unsuccessful response
    options:
      tags:
        - LDP
      description: Gets options for HTTP methods to utilize for this container
      parameters:
        - name: groupID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: UUID
      responses:
        "200":
          description: Successful response
          headers:
            Accept:
              type: array
              items:
                type: string
            Accept-Patch:
              type: array
              items:
                type: string
        "404":
          description: Unable to find container
        default:
          description: Unsuccessful response
    head:
      tags:
        - LDP
      description: Gets the header values that would normally be found in the header of GET
      parameters:
        - name: groupID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: UUID
      responses:
        "200":
          description: Successful response
          headers:
            Allow:
              type: array
              items:
                type: string
            Link:
              type: array
              items:
                type: string
                format: uri
        "404":
          description: Unable to find container
        default:
          description: Unsuccessful response
  /healthcheck:
    get:
      summary: Health Check
      description: The healthcheck endpoint provides information about the health of the service.
      operationId: healthCheck
      responses:
        '200':
          description: The service is functioning nominally
          schema:
            $ref: '#/definitions/HealthCheckResponse'
        '503':
          description: The service is not working correctly
          schema:
            $ref: '#/definitions/HealthCheckResponse'
definitions:
  HealthCheckResponse:
    type: object
    properties:
      status:
        type: string
        description: The status of the service
    example:
      status: OK
  ErrorResponse:
    type: object
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/Error'
  Error:
    type: object
    properties:
      title:
        type: string
        description: 'a short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem.'
        example: Invalid Attribute
      detail:
        type: string
        description: a human-readable explanation specific to this occurrence of the problem.
        example: Title must contain at least three characters.
      source:
        type: object
        properties:
          pointer:
            type: string
            example: /data/attributes/title
  LDPContainer:
    required:
      - containerID
      - name
      - URI
      - resources
    properties:
      containerID:
        type: string
      name:
        type: string
      URI:
        type: string
      resources:
        type: array
        items:
          $ref: '#/definitions/Resource'
  Resource:
    required:
      - "@graph"
      - "@id"
      - "@context"
    properties:
      "@graph":
        type: array
        items:
          type: object
          allOf:
            - $ref: "#/definitions/ResourceInfo"
      "@id":
        type: string
        format: uri
      "@context":
        $ref: "#/definitions/ResourceContext"
  ResourceInfo:
    required:
      - "@id"
      - "@type"
      - label
      - resource
    properties:
      "@id":
        type: string
        format: uri
      "@type":
        type: string
        format: uri
      label:
        type: string
      resource:
        type: string
        format: uri
  ResourceContext:
    required:
      - "@id"
      - "@type"
      - label
    properties:
      "@id":
        type: string
        format: uri
      "@type":
        type: string
        format: uri
      label:
        $ref: "#/definitions/variable"
  variable:
    type: object
    required:
      - "@id"
      - "@type"
    properties:
      "@id":
        type: string
        format: uri
      "@type":
        type: string
        format: uri
