defaults: &defaults
  docker:
    - image: circleci/node:10.11-browsers
  working_directory: ~/sinopia_server

version: 2
jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "sinopia_client/package.json" }}
      - run: cd sinopia_client && npm install
      - save_cache:
          key: node_modules-{{ checksum "sinopia_client/package.json" }}
          paths:
            - sinopia_client/node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "sinopia_client/package.json" }}
      - run: cd sinopia_client && npm run test

workflows:
  version: 2
  build:
    jobs:
      - dependencies
      - test:
          requires:
            - dependencies
