defaults: &defaults
  machine: true
  working_directory: ~/sinopia_server

version: 2
jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "sinopia_client/package.json" }}
      - run: cd sinopia_client && npm install
      - save_cache:
          key: node_modules-{{ checksum "sinopia_client/package.json" }}
          paths:
            - sinopia_client/node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "sinopia_client/package.json" }}
      - run:
          name: bring up trellis-ext-db, wait for it to start, run sinopia client integration tests
          command: |
            docker-compose up -d
            ./wait_for_healthy_trellis.sh
            cd sinopia_client
            npm run test

workflows:
  version: 2
  build:
    jobs:
      - dependencies
      - test:
          requires:
            - dependencies
