/**
 * Sinopia Server
 * Sinopia Server. Supports CRUD, following loosely LDP, on Sinopia resources. Top level requires special authorization for creating a group's graph (i.e. PCC, Stanford, etc.).
 *
 * OpenAPI spec version: 3.0.0-beta5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SinopiaServer) {
      root.SinopiaServer = {};
    }
    root.SinopiaServer.ResourceInfo = factory(root.SinopiaServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ResourceInfo model module.
   * @module model/ResourceInfo
   * @version 3.0.0-beta5
   */

  /**
   * Constructs a new <code>ResourceInfo</code>.
   * @alias module:model/ResourceInfo
   * @class
   * @param id {String} 
   * @param type {String} 
   * @param label {String} 
   * @param resource {String} 
   */
  var exports = function(id, type, label, resource) {
    var _this = this;

    _this['@id'] = id;
    _this['@type'] = type;
    _this['label'] = label;
    _this['resource'] = resource;
  };

  /**
   * Constructs a <code>ResourceInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResourceInfo} obj Optional instance to populate.
   * @return {module:model/ResourceInfo} The populated <code>ResourceInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('@id')) {
        obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
      }
      if (data.hasOwnProperty('@type')) {
        obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
      }
      if (data.hasOwnProperty('label')) {
        obj['label'] = ApiClient.convertToType(data['label'], 'String');
      }
      if (data.hasOwnProperty('resource')) {
        obj['resource'] = ApiClient.convertToType(data['resource'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} @id
   */
  exports.prototype['@id'] = undefined;
  /**
   * @member {String} @type
   */
  exports.prototype['@type'] = undefined;
  /**
   * @member {String} label
   */
  exports.prototype['label'] = undefined;
  /**
   * @member {String} resource
   */
  exports.prototype['resource'] = undefined;



  return exports;
}));


