/**
 * Sinopia Server
 * Sinopia Server. Supports CRUD, following loosely LDP, on Sinopia resources. Top level requires special authorization for creating a group's graph (i.e. PCC, Stanford, etc.).
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Variable'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Variable'));
  } else {
    // Browser globals (root is window)
    if (!root.SinopiaServer) {
      root.SinopiaServer = {};
    }
    root.SinopiaServer.ResourceContext = factory(root.SinopiaServer.ApiClient, root.SinopiaServer.Variable);
  }
}(this, function(ApiClient, Variable) {
  'use strict';




  /**
   * The ResourceContext model module.
   * @module model/ResourceContext
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ResourceContext</code>.
   * @alias module:model/ResourceContext
   * @class
   * @param id {String} 
   * @param type {String} 
   * @param label {module:model/Variable} 
   */
  var exports = function(id, type, label) {
    var _this = this;

    _this['@id'] = id;
    _this['@type'] = type;
    _this['label'] = label;
  };

  /**
   * Constructs a <code>ResourceContext</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResourceContext} obj Optional instance to populate.
   * @return {module:model/ResourceContext} The populated <code>ResourceContext</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('@id')) {
        obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
      }
      if (data.hasOwnProperty('@type')) {
        obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
      }
      if (data.hasOwnProperty('label')) {
        obj['label'] = Variable.constructFromObject(data['label']);
      }
    }
    return obj;
  }

  /**
   * @member {String} @id
   */
  exports.prototype['@id'] = undefined;
  /**
   * @member {String} @type
   */
  exports.prototype['@type'] = undefined;
  /**
   * @member {module:model/Variable} label
   */
  exports.prototype['label'] = undefined;



  return exports;
}));


