/**
 * Sinopia Server
 * Sinopia Server. Supports CRUD, following loosely LDP, on Sinopia resources. Top level requires special authorization for creating a group's graph (i.e. PCC, Stanford, etc.).
 *
 * OpenAPI spec version: 3.0.0-beta3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SinopiaServer) {
      root.SinopiaServer = {};
    }
    root.SinopiaServer.SinopiaBasicContainerContext = factory(root.SinopiaServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SinopiaBasicContainerContext model module.
   * @module model/SinopiaBasicContainerContext
   * @version 3.0.0-beta3
   */

  /**
   * Constructs a new <code>SinopiaBasicContainerContext</code>.
   * @alias module:model/SinopiaBasicContainerContext
   * @class
   * @param rdfs {String} 
   * @param ldp {String} 
   */
  var exports = function(rdfs, ldp) {
    var _this = this;

    _this['rdfs'] = rdfs;
    _this['ldp'] = ldp;
  };

  /**
   * Constructs a <code>SinopiaBasicContainerContext</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SinopiaBasicContainerContext} obj Optional instance to populate.
   * @return {module:model/SinopiaBasicContainerContext} The populated <code>SinopiaBasicContainerContext</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('rdfs')) {
        obj['rdfs'] = ApiClient.convertToType(data['rdfs'], 'String');
      }
      if (data.hasOwnProperty('ldp')) {
        obj['ldp'] = ApiClient.convertToType(data['ldp'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} rdfs
   */
  exports.prototype['rdfs'] = undefined;
  /**
   * @member {String} ldp
   */
  exports.prototype['ldp'] = undefined;



  return exports;
}));


