/**
 * Sinopia Server
 * Sinopia Server. Supports CRUD, following loosely LDP, on Sinopia resources. Top level requires special authorization for creating a group's graph (i.e. PCC, Stanford, etc.).
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorResponse', 'model/LDPContainer', 'model/Resource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ErrorResponse'), require('../model/LDPContainer'), require('../model/Resource'));
  } else {
    // Browser globals (root is window)
    if (!root.SinopiaServer) {
      root.SinopiaServer = {};
    }
    root.SinopiaServer.LDPApi = factory(root.SinopiaServer.ApiClient, root.SinopiaServer.ErrorResponse, root.SinopiaServer.LDPContainer, root.SinopiaServer.Resource);
  }
}(this, function(ApiClient, ErrorResponse, LDPContainer, Resource) {
  'use strict';

  /**
   * LDP service.
   * @module api/LDPApi
   * @version 1.0.0
   */

  /**
   * Constructs a new LDPApi. 
   * @alias module:api/LDPApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Get metadata for the base container.
     * Get the RDF metadata (default serialization is JSON-LD) for the base container.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LDPContainer} and HTTP response
     */
    this.getBaseWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['RemoteUser'];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = LDPContainer;

      return this.apiClient.callApi(
        '/repository', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get metadata for the base container.
     * Get the RDF metadata (default serialization is JSON-LD) for the base container.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LDPContainer}
     */
    this.getBase = function() {
      return this.getBaseWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Deletes LDP container 
     * @param {Number} groupID LDP Container to get
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.repositoryGroupIDDeleteWithHttpInfo = function(groupID) {
      var postBody = null;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling repositoryGroupIDDelete");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/repository/{groupID}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Deletes LDP container 
     * @param {Number} groupID LDP Container to get
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.repositoryGroupIDDelete = function(groupID) {
      return this.repositoryGroupIDDeleteWithHttpInfo(groupID)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Gets the header values that would normally be found in the header of GET
     * @param {Number} groupID LDP Container to get
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.repositoryGroupIDHeadWithHttpInfo = function(groupID) {
      var postBody = null;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling repositoryGroupIDHead");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/repository/{groupID}', 'HEAD',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Gets the header values that would normally be found in the header of GET
     * @param {Number} groupID LDP Container to get
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.repositoryGroupIDHead = function(groupID) {
      return this.repositoryGroupIDHeadWithHttpInfo(groupID)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Gets options for HTTP methods to utilize for this container
     * @param {Number} groupID LDP Container to get
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.repositoryGroupIDOptionsWithHttpInfo = function(groupID) {
      var postBody = null;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling repositoryGroupIDOptions");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/repository/{groupID}', 'OPTIONS',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Gets options for HTTP methods to utilize for this container
     * @param {Number} groupID LDP Container to get
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.repositoryGroupIDOptions = function(groupID) {
      return this.repositoryGroupIDOptionsWithHttpInfo(groupID)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Updates LDP container 
     * @param {Number} groupID LDP Container to get
     * @param {module:model/Resource} resource Resource to insert into container
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.repositoryGroupIDPatchWithHttpInfo = function(groupID, resource) {
      var postBody = resource;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling repositoryGroupIDPatch");
      }

      // verify the required parameter 'resource' is set
      if (resource === undefined || resource === null) {
        throw new Error("Missing the required parameter 'resource' when calling repositoryGroupIDPatch");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/repository/{groupID}', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Updates LDP container 
     * @param {Number} groupID LDP Container to get
     * @param {module:model/Resource} resource Resource to insert into container
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.repositoryGroupIDPatch = function(groupID, resource) {
      return this.repositoryGroupIDPatchWithHttpInfo(groupID, resource)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create new Group.
     * Create a resource (defined via JSON-LD in payload) within a Group.
     * @param {String} groupID The group (ldp:Container) who is defining it&#39;s own resources or graph within Sinopia.
     * @param {module:model/Resource} resource Resource to insert into container
     * @param {Object} opts Optional parameters
     * @param {String} opts.slug Suggested URI for resource
     * @param {String} opts.contentType Content-Type of resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.repositoryGroupIDPostWithHttpInfo = function(groupID, resource, opts) {
      opts = opts || {};
      var postBody = resource;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling repositoryGroupIDPost");
      }

      // verify the required parameter 'resource' is set
      if (resource === undefined || resource === null) {
        throw new Error("Missing the required parameter 'resource' when calling repositoryGroupIDPost");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Slug': opts['slug'],
        'Content-Type': opts['contentType']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/repository/{groupID}', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Create new Group.
     * Create a resource (defined via JSON-LD in payload) within a Group.
     * @param {String} groupID The group (ldp:Container) who is defining it&#39;s own resources or graph within Sinopia.
     * @param {module:model/Resource} resource Resource to insert into container
     * @param {Object} opts Optional parameters
     * @param {String} opts.slug Suggested URI for resource
     * @param {String} opts.contentType Content-Type of resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.repositoryGroupIDPost = function(groupID, resource, opts) {
      return this.repositoryGroupIDPostWithHttpInfo(groupID, resource, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Updates the group description.
     * @param {Number} groupID LDP Container to get
     * @param {module:model/Resource} resource Resource to insert into container
     * @param {Object} opts Optional parameters
     * @param {String} opts.slug Suggested URI for resource
     * @param {String} opts.contentType Content-Type of resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.repositoryGroupIDPutWithHttpInfo = function(groupID, resource, opts) {
      opts = opts || {};
      var postBody = resource;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling repositoryGroupIDPut");
      }

      // verify the required parameter 'resource' is set
      if (resource === undefined || resource === null) {
        throw new Error("Missing the required parameter 'resource' when calling repositoryGroupIDPut");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Slug': opts['slug'],
        'Content-Type': opts['contentType']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/repository/{groupID}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Updates the group description.
     * @param {Number} groupID LDP Container to get
     * @param {module:model/Resource} resource Resource to insert into container
     * @param {Object} opts Optional parameters
     * @param {String} opts.slug Suggested URI for resource
     * @param {String} opts.contentType Content-Type of resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.repositoryGroupIDPut = function(groupID, resource, opts) {
      return this.repositoryGroupIDPutWithHttpInfo(groupID, resource, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get headers only of base container request.
     * Gets the header values that would normally be found in the header of GET on base container
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.repositoryHeadWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/repository', 'HEAD',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get headers only of base container request.
     * Gets the header values that would normally be found in the header of GET on base container
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.repositoryHead = function() {
      return this.repositoryHeadWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Gets options for HTTP methods to utilize for the base container.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.repositoryOptionsWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/repository', 'OPTIONS',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Gets options for HTTP methods to utilize for the base container.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.repositoryOptions = function() {
      return this.repositoryOptionsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create new Group within the base container.
     * Create a new Group (defined via JSON-LD in payload) within the base container.
     * @param {module:model/Resource} groupMD Group metadata to insert into base container and describe the group.
     * @param {Object} opts Optional parameters
     * @param {String} opts.slug The group (ldp:Container) who is defining it&#39;s own entities or graph within Sinopia.
     * @param {String} opts.contentType Content-Type of resource, with preference for JSON-LD.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.repositoryPostWithHttpInfo = function(groupMD, opts) {
      opts = opts || {};
      var postBody = groupMD;

      // verify the required parameter 'groupMD' is set
      if (groupMD === undefined || groupMD === null) {
        throw new Error("Missing the required parameter 'groupMD' when calling repositoryPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Slug': opts['slug'],
        'Content-Type': opts['contentType']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/repository', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Create new Group within the base container.
     * Create a new Group (defined via JSON-LD in payload) within the base container.
     * @param {module:model/Resource} groupMD Group metadata to insert into base container and describe the group.
     * @param {Object} opts Optional parameters
     * @param {String} opts.slug The group (ldp:Container) who is defining it&#39;s own entities or graph within Sinopia.
     * @param {String} opts.contentType Content-Type of resource, with preference for JSON-LD.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.repositoryPost = function(groupMD, opts) {
      return this.repositoryPostWithHttpInfo(groupMD, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update metadata on base container.
     * Update metadata of base container with new metadata defined via JSON-LD in payload. Performs overwrite, not partial update.
     * @param {module:model/Resource} metadata New base container metadata to assert on the container.
     * @param {Object} opts Optional parameters
     * @param {String} opts.contentType Content-Type of resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.repositoryPutWithHttpInfo = function(metadata, opts) {
      opts = opts || {};
      var postBody = metadata;

      // verify the required parameter 'metadata' is set
      if (metadata === undefined || metadata === null) {
        throw new Error("Missing the required parameter 'metadata' when calling repositoryPut");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Content-Type': opts['contentType']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/repository', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Update metadata on base container.
     * Update metadata of base container with new metadata defined via JSON-LD in payload. Performs overwrite, not partial update.
     * @param {module:model/Resource} metadata New base container metadata to assert on the container.
     * @param {Object} opts Optional parameters
     * @param {String} opts.contentType Content-Type of resource
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.repositoryPut = function(metadata, opts) {
      return this.repositoryPutWithHttpInfo(metadata, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
