/**
 * Sinopia Server
 * Sinopia Server. Supports CRUD, following loosely LDP, on Sinopia resources. Top level requires special authorization for creating a group's graph (i.e. PCC, Stanford, etc.).
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Resource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Resource'));
  } else {
    // Browser globals (root is window)
    if (!root.SinopiaServer) {
      root.SinopiaServer = {};
    }
    root.SinopiaServer.LDPApi = factory(root.SinopiaServer.ApiClient, root.SinopiaServer.Resource);
  }
}(this, function(ApiClient, Resource) {
  'use strict';

  /**
   * LDP service.
   * @module api/LDPApi
   * @version 0.0.1
   */

  /**
   * Constructs a new LDPApi. 
   * @alias module:api/LDPApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the groupIDDelete operation.
     * @callback module:api/LDPApi~groupIDDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes LDP container 
     * @param {Number} groupID LDP Container to get
     * @param {module:api/LDPApi~groupIDDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.groupIDDelete = function(groupID, callback) {
      var postBody = null;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling groupIDDelete");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{groupID}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the groupIDHead operation.
     * @callback module:api/LDPApi~groupIDHeadCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets the header values that would normally be found in the header of GET
     * @param {Number} groupID LDP Container to get
     * @param {module:api/LDPApi~groupIDHeadCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.groupIDHead = function(groupID, callback) {
      var postBody = null;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling groupIDHead");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{groupID}', 'HEAD',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the groupIDOptions operation.
     * @callback module:api/LDPApi~groupIDOptionsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets options for HTTP methods to utilize for this container
     * @param {Number} groupID LDP Container to get
     * @param {module:api/LDPApi~groupIDOptionsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.groupIDOptions = function(groupID, callback) {
      var postBody = null;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling groupIDOptions");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{groupID}', 'OPTIONS',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the groupIDPatch operation.
     * @callback module:api/LDPApi~groupIDPatchCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates LDP container 
     * @param {Number} groupID LDP Container to get
     * @param {module:model/Resource} resource Resource to insert into container
     * @param {module:api/LDPApi~groupIDPatchCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.groupIDPatch = function(groupID, resource, callback) {
      var postBody = resource;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling groupIDPatch");
      }

      // verify the required parameter 'resource' is set
      if (resource === undefined || resource === null) {
        throw new Error("Missing the required parameter 'resource' when calling groupIDPatch");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{groupID}', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the groupIDPost operation.
     * @callback module:api/LDPApi~groupIDPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create new Group.
     * Create a resource (defined via JSON-LD in payload) within a Group.
     * @param {String} groupID The group (ldp:Container) who is defining it&#39;s own resources or graph within Sinopia.
     * @param {module:model/Resource} resource Resource to insert into container
     * @param {Object} opts Optional parameters
     * @param {String} opts.slug Suggested URI for resource
     * @param {String} opts.contentType Content-Type of resource
     * @param {module:api/LDPApi~groupIDPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.groupIDPost = function(groupID, resource, opts, callback) {
      opts = opts || {};
      var postBody = resource;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling groupIDPost");
      }

      // verify the required parameter 'resource' is set
      if (resource === undefined || resource === null) {
        throw new Error("Missing the required parameter 'resource' when calling groupIDPost");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Slug': opts['slug'],
        'Content-Type': opts['contentType']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{groupID}', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the groupIDPut operation.
     * @callback module:api/LDPApi~groupIDPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates the group description.
     * @param {Number} groupID LDP Container to get
     * @param {module:model/Resource} resource Resource to insert into container
     * @param {Object} opts Optional parameters
     * @param {String} opts.slug Suggested URI for resource
     * @param {String} opts.contentType Content-Type of resource
     * @param {module:api/LDPApi~groupIDPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.groupIDPut = function(groupID, resource, opts, callback) {
      opts = opts || {};
      var postBody = resource;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling groupIDPut");
      }

      // verify the required parameter 'resource' is set
      if (resource === undefined || resource === null) {
        throw new Error("Missing the required parameter 'resource' when calling groupIDPut");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Slug': opts['slug'],
        'Content-Type': opts['contentType']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{groupID}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the resourcesDelete operation.
     * @callback module:api/LDPApi~resourcesDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes LDP container 
     * @param {Number} groupID LDP Container to get
     * @param {module:api/LDPApi~resourcesDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.resourcesDelete = function(groupID, callback) {
      var postBody = null;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling resourcesDelete");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/resources', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the resourcesHead operation.
     * @callback module:api/LDPApi~resourcesHeadCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets the header values that would normally be found in the header of GET
     * @param {Number} groupID LDP Container to get
     * @param {module:api/LDPApi~resourcesHeadCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.resourcesHead = function(groupID, callback) {
      var postBody = null;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling resourcesHead");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/resources', 'HEAD',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the resourcesOptions operation.
     * @callback module:api/LDPApi~resourcesOptionsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets options for HTTP methods to utilize for this container
     * @param {Number} groupID LDP Container to get
     * @param {module:api/LDPApi~resourcesOptionsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.resourcesOptions = function(groupID, callback) {
      var postBody = null;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling resourcesOptions");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/resources', 'OPTIONS',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the resourcesPatch operation.
     * @callback module:api/LDPApi~resourcesPatchCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates LDP container
     * @param {module:model/Resource} resource Group to insert into baseline container.
     * @param {module:api/LDPApi~resourcesPatchCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.resourcesPatch = function(resource, callback) {
      var postBody = resource;

      // verify the required parameter 'resource' is set
      if (resource === undefined || resource === null) {
        throw new Error("Missing the required parameter 'resource' when calling resourcesPatch");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/resources', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the resourcesPost operation.
     * @callback module:api/LDPApi~resourcesPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create new Group within the base container.
     * Create a new Group (defined via JSON-LD in payload) within the baseline container.
     * @param {String} groupID The group (ldp:Container) who is defining it&#39;s own entities or graph within Sinopia.
     * @param {module:model/Resource} groupMD Group metadata to insert into base container and describe the group.
     * @param {Object} opts Optional parameters
     * @param {String} opts.contentType Content-Type of resource, with preference for JSON-LD.
     * @param {module:api/LDPApi~resourcesPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.resourcesPost = function(groupID, groupMD, opts, callback) {
      opts = opts || {};
      var postBody = groupMD;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling resourcesPost");
      }

      // verify the required parameter 'groupMD' is set
      if (groupMD === undefined || groupMD === null) {
        throw new Error("Missing the required parameter 'groupMD' when calling resourcesPost");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Content-Type': opts['contentType']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/resources', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the resourcesPut operation.
     * @callback module:api/LDPApi~resourcesPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create new Group within the baseline container.
     * Create a new Group (defined via JSON-LD in payload) within the baseline container.
     * @param {String} groupID The group (ldp:Container) who is defining it&#39;s own resources or graph within Sinopia.
     * @param {module:model/Resource} resource Resource to insert into container
     * @param {Object} opts Optional parameters
     * @param {String} opts.slug Suggested URI for resource
     * @param {String} opts.contentType Content-Type of resource
     * @param {module:api/LDPApi~resourcesPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.resourcesPut = function(groupID, resource, opts, callback) {
      opts = opts || {};
      var postBody = resource;

      // verify the required parameter 'groupID' is set
      if (groupID === undefined || groupID === null) {
        throw new Error("Missing the required parameter 'groupID' when calling resourcesPut");
      }

      // verify the required parameter 'resource' is set
      if (resource === undefined || resource === null) {
        throw new Error("Missing the required parameter 'resource' when calling resourcesPut");
      }


      var pathParams = {
        'groupID': groupID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Slug': opts['slug'],
        'Content-Type': opts['contentType']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json+ld'];
      var accepts = ['application/json+ld'];
      var returnType = null;

      return this.apiClient.callApi(
        '/resources', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
