/**
 * Sinopia Server
 * Sinopia Server. Supports CRUD, following loosely LDP, on Sinopia resources. Top level requires special authorization for creating a group's graph (i.e. PCC, Stanford, etc.).
 *
 * OpenAPI spec version: 3.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SinopiaServer);
  }
}(this, function(expect, SinopiaServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SinopiaServer.DefaultApi();
    // same idea as https://stackoverflow.com/a/36041786
    instance.apiClient.basePath = 'http://localhost:8080';
  });

  describe('DefaultApi', function() {
    describe('healthCheck', function() {
      beforeEach(function() {
        instance.apiClient.basePath = 'http://localhost:8081';
      });
      it('should call healthCheck successfully', function() {
        // Application health checks are available at http://localhost:8081/healthcheck
        // see https://github.com/trellis-ldp/trellis-ext-db/blob/22efbc5bc3e12bfae41e06536c498a0e659ce98f/deployment/src/dist/README.md
        return instance.healthCheck()
          .then(function(data) {
            expect(data).to.be.a(SinopiaServer.HealthCheckResponse);
          });
      });
    });
  });
}));
